region = "us-east-1"
ecr_name = "isengardecr-dev"
dynamodb_table_name = "dynamodb_table_nithin"
env = "dev"
images_to_keep= 15
owner_tag = "nithin-101"
project = "xerris-dev-101"
bucket_name = "test-bucket-xerris-nithin"
sqs_name = "test-sqs-nithin"