name: 'Deployment'
on:
  push:
    branches:
    - master
    - XDP-*
  #pull_request:
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@master
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2
    - name: Inject SSH Credentials
      uses: PhutureCorp/container-ssh-agent@v0.0.1
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        home-dir: "/home/runner"
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.14.6
    - name: Run Terraform Plan
      run: |
        pwd
        export ENV=poc
        sh terraform_exec.sh 0

    - name: Run Terraform Apply
      run: |
        export ENV=poc
        sh terraform_exec.sh 1